### ISSUE TITLE
Bug on ubuntu 15.10 "AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'"

### ISSUE THREAD

**Issue by brodul** [brodul/najdi-si-sms#2]
Traceback (most recent call last):
      File "/usr/local/bin/najdisi-sms", line 9, in <module>
        load_entry_point('najdisi-sms==0.3.1', 'console_scripts', 'najdisi-sms')()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 558, in load_entry_point
        return get_distribution(dist).load_entry_point(group, name)
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2682, in load_entry_point
        return ep.load()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2355, in load
        return self.resolve()
      File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2361, in resolve
        module = __import__(self.module_name, fromlist=['__name__'], level=0)
      File "/usr/local/lib/python2.7/dist-packages/najdisi_sms.py", line 7, in <module>
        import requests
      File "/usr/local/lib/python2.7/dist-packages/requests/__init__.py", line 53, in <module>
        from .packages.urllib3.contrib import pyopenssl
      File "/usr/local/lib/python2.7/dist-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 62, in <module>
        ssl.PROTOCOL_SSLv3: OpenSSL.SSL.SSLv3_METHOD,
    AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'

**Comment by brodul** [comment]
Fixed with the `requests` update
