### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by marksev1** [brodul/najdi-si-sms#3]
Če iz terminala na orange piju poizkusm pognat dobim tole:
```

msev@orangepipc:~/libraries/mycroft-core-release-v0.7.7$ najdisi-sms -u msev -p password 041222222 test of system
Traceback (most recent call last):
  File "/usr/local/bin/najdisi-sms", line 9, in <module>
    load_entry_point('najdisi-sms==1.0.1', 'console_scripts', 'najdisi-sms')()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/local/lib/python3.4/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python3.4/dist-packages/najdisi_sms/__init__.py", line 6, in <module>
    from .cli import SMSSender
  File "/usr/local/lib/python3.4/dist-packages/najdisi_sms/cli.py", line 7, in <module>
    import utils
ImportError: No module named 'utils'
```

A mi lahko pomagaš?

**Comment by brodul** [comment]
Lahko v konzolo napises `/usr/local/lib/python3.4/dist-packages/najdisi_sms/`.

**Comment by brodul** [comment]
Tukaj sem ti pokomentiral kodo.

https://github.com/marksev1/mycroft-core/commit/21802f3a68d6406ad6ace73d88d29d7dcb3bd24c

**Comment by marksev1** [comment]
Brodul zanima me samo zakaj iz terminala direkt ne dela (k maš cli varianto svojga programa tut). Iz skript mi zj dela like a boss.

**Comment by brodul** [comment]
Nice. Ne vem moral bi bolj pogledat. Mas ubuntu? Katero verzijo?

**Comment by marksev1** [comment]
Na orange-piju mam armbian ki je debian jessie 8 derivative. In to
serversko verzijo tko da je pomoje jessie lite derivat.

6. okt. 2016 15.37 je oseba "Andraz Brodnik" <notifications@github.com>
napisala:
